import { describe, expect, it } from "vitest";
import ExcelJS from "exceljs";

import {
  buildMasterWorkbook,
  buildSingleCheckInWorkbook,
} from "@/lib/excel/check-in-workbooks";
import { makeFields } from "@/tests/helpers/check-in-test-data";

describe("check-in workbook generation", () => {
  it("builds the polished single-truck workbook with formatted load weight, AM/PM times, and delay logic", async () => {
    const buffer = await buildSingleCheckInWorkbook({
      fields: makeFields({
        quantity: "28,000.50",
        arrivalTime: "13:15",
        departureTime: "15:45",
      }),
      submittedAt: "2026-04-22T18:30:00.000Z",
      reviewStatus: "reviewed",
      manuallyEditedFields: ["comments", "vehicleNumber"],
      exportGeneratedAt: "2026-04-22T18:45:00.000Z",
    });

    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer);
    const worksheet = workbook.getWorksheet("Check-In");

    expect(worksheet.getCell("A1").value).toBe("HOT LOAD CHECK-IN");
    expect(worksheet.getCell("A2").value).toBe("Gerdau – Manager");
    expect(worksheet.getCell("A1").isMerged).toBe(true);
    expect(worksheet.views[0]?.ySplit).toBe(2);
    expect(worksheet.getCell("B9").value).toBe("28,000.50 LB");
    expect(worksheet.getCell("B17").numFmt).toBe("h:mm AM/PM");
    expect(worksheet.getCell("B18").numFmt).toBe("h:mm AM/PM");
    expect(worksheet.getCell("B19").value).toBeInstanceOf(Date);
    expect((worksheet.getCell("B19").value as Date).getUTCHours()).toBe(2);
    expect((worksheet.getCell("B19").value as Date).getUTCMinutes()).toBe(30);
    expect(worksheet.getCell("B19").numFmt).toBe("[h]:mm");
    expect(worksheet.getCell("B20").value).toBe("Yes");
    expect(worksheet.getCell("B26").numFmt).toBe("m/d/yyyy h:mm AM/PM");
    expect(worksheet.getCell("B27").value).toBe("reviewed");
    expect(worksheet.getCell("B28").value).toBe("Edited: Comments, Vehicle Number");
    expect(worksheet.getCell("A30").value).toBe("Generated by Hot Load Check-In");
    expect(worksheet.getCell("A31").numFmt).toBe('"Export Generated: "m/d/yyyy h:mm AM/PM');
    expect(worksheet.conditionalFormattings).toHaveLength(2);
    expect(worksheet.conditionalFormattings[0]?.rules).toHaveLength(3);
    expect(worksheet.conditionalFormattings[1]?.rules).toHaveLength(1);
  });

  it("builds the master export with appended operational columns and analysis-friendly duration formatting", async () => {
    const buffer = await buildMasterWorkbook([
      {
        fields: makeFields(),
        submissionStatus: "succeeded",
        exportStatus: "succeeded",
        emailStatus: "succeeded",
        submittedAt: "2026-04-22T18:30:00.000Z",
      },
    ]);

    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer);
    const worksheet = workbook.getWorksheet("Check-In");
    const headerValues = worksheet.getRow(1).values as Array<string | null>;

    expect(headerValues.slice(1)).toEqual([
      "Date",
      "Ticket Number",
      "Vendor",
      "Material",
      "Quantity",
      "Truck Number",
      "Arrival Time",
      "Departure Time",
      "Comments",
      "Vehicle Number",
      "RAD Ticket",
      "HARSCO Employee",
      "Time On Site",
      "Submission Status",
      "Export Status",
      "Email Status",
      "Submitted At",
    ]);
    expect(worksheet.getCell("G2").value).toBe("1:50 PM");
    expect(worksheet.getCell("H2").value).toBe("3:29 PM");
    expect(worksheet.getCell("M2").numFmt).toBe("[h]:mm");
    expect(worksheet.getCell("N2").value).toBe("succeeded");
    expect(worksheet.getCell("Q2").numFmt).toBe("m/d/yyyy h:mm AM/PM");
  });
});
